export const productos =  [
    {id: 1, title: "Alimento", category: 1, price: 2000, description: "Lorem ipsum dolor sit amet, consectetur adipisci elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam" , pictureUrl: "https://kangoopet.com.ar/wp-content/uploads/2020/04/MINI_PUPPY_01.jpg"},
    {id: 2, title: "Pelota", category: 1, price: 800, description: "Lorem ipsum dolor sit amet, consectetur adipisci elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam", pictureUrl: "https://www.paticas.es/imagenes/image/productos/34390_1_pelota-gomaespuma-flotable-para-perro.jpg"},
    {id: 3, title:"Comedero", category: 1, price: 1500, description: "Lorem ipsum dolor sit amet, consectetur adipisci elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam", pictureUrl: "http://d3ugyf2ht6aenh.cloudfront.net/stores/555/698/products/preview-tienda-nube-2-0-921-e2460a53373f3bdad615384262641683-640-0.jpg"},
    {id: 4, title: "Correa", category: 1, price: 1200, description: "Lorem ipsum dolor sit amet, consectetur adipisci elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam", pictureUrl:"https://th.bing.com/th/id/R.488ddbe7fa5d6246d52ecf493a7165ce?rik=5DAxMbJ%2beWTgmw&riu=http%3a%2f%2fwww.paticas.es%2fimagenes%2fImage%2fProductos%2fHL12-BW_1_correa-scooter-huesos-para-perros-2.jpg&ehk=3KUt6B9uQIHDTukaxX3r57O5ZDlYyC92Ko7U4R%2bIB%2f8%3d&risl=&pid=ImgRaw&r=0"},
    {id: 5, title: "Rascador", category: 2, price: 3000, description: "Lorem ipsum dolor sit amet, consectetur adipisci elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam", pictureUrl:"https://www.paticas.es/imagenes/image/productos/43089_2_poste-rascador-gato-rojo.jpg"},
    {id: 6, title: "Alimento", category: 2, price: 1600, description: "Lorem ipsum dolor sit amet, consectetur adipisci elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam", pictureUrl:"https://res.cloudinary.com/walmart-labs/image/upload/w_960,dpr_auto,f_auto,q_auto:best/gr/images/product-images/img_large/00750177700115L.jpg"}
]



